<?php

/**
 * @file
 * Shows issue information on periodicals.
 */

// Load Field module hooks.
module_load_include('inc', 'ding_periodical', 'ding_periodical.field');

/**
 * Implements hook_theme().
 */
function ding_periodical_theme() {
  return array(
    'ding_periodical_issues' => array(
      'render element' => 'elements',
    ),
  );
}

/**
 * Theming function.
 */
function theme_ding_periodical_issues($variables) {
  $items = array();
  watchdog('Periodical availability Log:',json_encode($variables['elements']['#issues']), array(), WATCHDOG_NOTICE, $link = NULL);
  foreach ($variables['elements']['#issues'] as $volume => $issues) {
    $iss = array();
    foreach ($issues as $key => $availability) {
      $issue = $key;
      $issue_holding = '';
      // check user
      if ($availability['reservable'] && module_exists('ding_periodical_reservation')) {
        $issue_holding = ' ' . ding_periodical_reservation_button($availability['local_id'], $volume, $key, $variables['elements']['#entity']);
      }
      $issue_holding .= '<h2>' . t('Holdings') . '</h2>';
      $issue_holding .= '<p>' . format_plural($availability['total_count'], 'We have 1 copy (@reservable_count reservable).', 'We have @count copies (@reservable_count reservable).', array('@reservable_count' => $availability['reservable_count'])) . '</p>';
      $issue_holding .= '<ul class="holdings">';
      foreach ($availability['holdings'] as $holding) {
        $issue_holding .= '<li';
        $issue_holding .= ($holding['available_count'] > 0) ? ' class=available' : ' class=unavailable';
        $issue_holding .= '>';
        $issue_holding .= join(' → ', $holding['location']);
        $issue_holding .= format_plural($holding['available_count'], '(1 copy home)', '(@count copies home)');
        $issue_holding .= '</li>';
      }
      $issue_holding .= '</ul>';
      $iss[] = array(
        'data' => '<div class="' . drupal_html_class('ding_periodical_fold').'">' . $issue . '</div>',
        'children' => array($issue_holding),
        'class' => array(drupal_html_class('ding_periodical_foldable')),
      );
    }

    $vol = array(
      'data' => '<div class="' . drupal_html_class('ding_periodical_fold').'">' . $volume . '</div>',
      'children' => $iss,
      'class' => array(drupal_html_class('ding_periodical_foldable')),
    );
    $items[] = $vol;
  }

  return theme('item_list', array('items' => $items, 'attributes' => array('class' => drupal_html_class('ding_periodical_issues'))));
}
